# Generated by Django 2.2.17 on 2020-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_jhgjhg"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="gsdf",
            field=models.CharField(blank=True, max_length=27034524354563, null=True),
        ),
    ]
