# Generated by Django 2.2.17 on 2020-11-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_customtext_gsdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtext",
            name="gsdf",
        ),
    ]
